Create a Deployment named as ic-deploy-nautilus.

Configure spec as replicas should be 1, labels app should be ic-nautilus, template's metadata lables app should be the same ic-nautilus.

The initContainers should be named as ic-msg-nautilus, use image centos, preferably with latest tag and use command '/bin/bash', '-c' and 'echo Init Done - Welcome to xFusionCorp Industries > /ic/blog'.
The volume mount should be named as ic-volume-nautilus and mount path should be /ic.

Main container should be named as ic-main-nautilus, use image centos, preferably with latest tag and use command '/bin/bash', '-c' and 'while true; do cat /ic/blog; sleep 5; done'.
 The volume mount should be named as ic-volume-nautilus and mount path should be /ic.

Volume to be named as ic-volume-nautilus and it should be an emptyDir type.

apiVersion: apps/v1
kind: Deployment
metadata:
 name: ic-deploy-nautilus
 labels:
  app: ic-nautilus
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ic-nautilus
 template:
  metadata:
   labels:
    app: ic-nautilus
  spec:
   initContainers:
    - name: ic-msg-nautilus
      image: centos:latest
      command:
      - '/bin/bash'
      - '-c'
      - 'echo Init Done - Welcome to xFusionCorp Industries > /ic/blog'
      volumeMounts:
       - name: ic-volume-nautilus
         mountPath: /ic
   containers:
    - name: ic-main-nautilus
      image: centos:latest
      command:
      - '/bin/bash'
      - '-c'
      - 'while true; do cat /ic/blog; sleep 5; done'
      volumeMounts:
      - name: ic-volume-nautilus
        mountPath: /ic
   volumes:
    - name: ic-volume-nautilus
      emptyDir: {}
