#The Nautilus DevOps team discussed how they can train different team members to use Ansible for different automation tasks.
#There are numerous ways to perform a particular task using Ansible, but we want to utilize each aspect Ansible offers so the team wants to utilise Ansible's conditionals to perform the following task:

#An inventory file is already placed under /home/thor/ansible on jump host, with all the Stratos DC app servers included.

#Create a playbook /home/thor/ansible/playbook.yml and make sure to use Ansible's when conditionals statements to perform the following tasks.

#Copy blog.txt file present under /usr/src/itadmin directory on jump host to App Server 1 under /opt/itadmin directory. Its user and group owner must be user tony and its permissions must be 0644 .

#Copy story.txt file present under /usr/src/itadmin directory on jump host to App Server 2 under /opt/itadmin directory. Its user and group owner must be user steve and its permissions must be 0644 .

#Copy media.txt file present under /usr/src/itadmin directory on jump host to App Server 3 under /opt/itadmin directory. Its user and group owner must be user banner and its permissions must be 0644 .

#NOTE: You can use ansible_nodename variable from gathered facts with when condition. Additionally, please make sure you are running the play for all hosts i.e use - hosts: all.

#Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml, so please make sure playbook works this way, without passing any extra arguments.


- name: check conditions
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
  - name: Copy file on stapp01
    copy:
     src: /usr/src/itadmin/blog.txt
     dest: /opt/itadmin
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
     mode: 0644
    when: inventory_hostname == "stapp01"
  - name: Copy file on stapp02
    copy:
     src: /usr/src/itadmin/story.txt
     dest: /opt/itadmin
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
     mode: 0644
    when: inventory_hostname == "stapp02"
  - name: Copy file on stapp03
    copy:
     src: /usr/src/itadmin/media.txt
     dest: /opt/itadmin
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
     mode: 0644
    when: inventory_hostname == "stapp03"
...